### PR TITLE
Fix UBSan issue

### LINKED ISSUE #1601: Clang UBSan alignment error in tbb::concurrent_hash_map::hash_map_iterator constructor
# Summary
UBSan reports an error in the `tbb::concurrent_hash_map::hash_map_iterator` constructor. It looks like the same error as the one reported for the `hash_map_iterator::advance_to_next_bucket` UBSan failure [here](https://github.com/uxlfoundation/oneTBB/issues/908).

```
    template<typename Container, typename Value>
    hash_map_iterator<Container,Value>::hash_map_iterator( const Container &map, size_t index, const bucket *b, node_base *n ) :
        my_map(&map),
        my_index(index),
        my_bucket(b),
        my_node( static_cast<node*>(n) )          // <-- UB static_cast to node*, as n is 0x3. It is not an 8-byte aligned address.
    {
        if( b && !hash_map_base::is_valid(n) )
            advance_to_next_bucket();
    }
```

# Version
TBB version 2020.3

# Environment
Rocky8
Clang 14.0.3

# Observed Behavior
When using `tbb::concurrent_hash_map::range()` undefined behavior sanitizer generates this error:
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /path_to_tbb/tbb/2020.3/include/tbb/concurrent_hash_map.h:442:18 in 
/path_to_tbb/tbb/2020.3/include/tbb/concurrent_hash_map.h:377:27: runtime error: downcast of misaligned address 0x000000000003 for type 'tbb::interface5::internal::hash_map_iterator<tbb::interface5::concurrent_hash_map<int, int>, std::pair<const int, int>>::node' (aka 'tbb::interface5::concurrent_hash_map<int, int>::node'), which requires 8 byte alignment
0x000000000003: note: pointer points here
```

# Expected Behavior
Undefined behavior sanitizer should not generate any errors when using `tbb::concurrent_hash_map::range()` 

# Steps To Reproduce

Paste into tbb-concurrent_hash_map-ubsan.cpp:
```
#include <tbb/concurrent_hash_map.h>

int
main()
{
  tbb::concurrent_hash_map<int, int> map;

  map.insert({0, 0});
  auto r = map.range();

  return 0;
}
```

Compile with: `clang++ -g -fsanitize=undefined tbb-concurrent_hash_map-ubsan.cpp -o tbb-concurrent_hash_map-ubsan -ltbb`

I fixed this locally by changing the hash_map_iterator constructor to this:
```

hash_map_iterator(const HashMapType& map,
                                                                    size_t             index,
                                                                    const bucket*      b,
                                                                    node_base*         n)
    : my_map(&map), my_index(index), my_bucket(b), my_node(nullptr) {
    if (b) {
        if (!hash_map_base::is_valid(n))
            advance_to_next_bucket();
        else
            my_node = static_cast<node*>(n);
    }
}

### PR DESCRIPTION
**Pull request by dnmokhov**
### Description 
UBSan reports an error if we try to downcast a misaligned address. To avoid it, we need to check if an address is valid before casting it.

Here is the UBSan error:
```
concurrent_hash_map.h:470:62: runtime error: downcast of misaligned address 0x000000000003 for type 'node' (aka 'tbb::detail::d2::concurrent_hash_map<int, int>::node'), which requires 8 byte alignment
0x000000000003: note: pointer points here
<memory cannot be printed>
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior concurrent_hash_map.h:470:62
```

Fixes #1601

### Type of change
- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests
- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation
- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### CODE REVIEW

File: include/oneapi/tbb/concurrent_hash_map.h [hunk 1]
```diff
@@ -467,9 +467,11 @@ class hash_map_iterator {
     friend class concurrent_hash_map;
 
     hash_map_iterator( const Container &map, std::size_t index, const bucket *b, node_base *n ) :
-        my_map(&map), my_index(index), my_bucket(b), my_node(static_cast<node*>(n))
+        my_map(&map), my_index(index), my_bucket(b), my_node(nullptr)
     {
-        if( b && !map_base::is_valid(n) )
+        if( map_base::is_valid(n) )
+            my_node = static_cast<node*>(n);
```
Comment (kboyarinov) [inline include/oneapi/tbb/concurrent_hash_map.h:473]: Can you please add a comment in the code why we cannot do the cast during the initialization?

**Review by kboyarinov — COMMENTED** [review]
LGTM

File: include/oneapi/tbb/concurrent_hash_map.h (hunk 1 above)
Comment (dnmokhov) [reply include/oneapi/tbb/concurrent_hash_map.h:475]: Added.
